name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      XDG_CACHE_HOME: $HOME/.ci-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          cargo nextest run --locked --all-features
          cargo nextest run --locked --all-features --benches
          LD_LIBRARY_PATH="$(rustc --print target-libdir)" cargo test --locked --all-features --doc

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        run: cargo check --locked --all-features
      - name: Run cargo clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Check for typos
        uses: crate-ci/typos@v1.36.2
      - name: Typos info
        if: failure()
        run: |
          echo 'To fix typos, please run `typos -w`'
          echo 'To check for a diff, run `typos`'
          echo 'You can find typos here: https://crates.io/crates/typos'
          echo 'if you use VSCode, you can also install `Typos Spell Checker'
          echo 'You can find the extension here: https://marketplace.visualstudio.com/items?itemName=tekumara.typos-vscode'

  check_compiles:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Check crates compile on stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run build
        run: cargo build --locked --workspace --all-features

  validate-commits:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Validate commit messages
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: taiki-e/install-action@v2
        with:
          tool: committed

      - name: check commit messages
        run: committed origin/${{ github.event.repository.default_branch }}..HEAD
